-- MySQL Script generated by MySQL Workbench
-- Mon Dec 30 17:30:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livreur` (
  `idLivreur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `longitude` DECIMAL NULL,
  `latitude` DECIMAL NULL,
  PRIMARY KEY (`idLivreur`))
ENGINE = InnoDB;

INSERT INTO `livreur` (`idLivreur`, `nom`, `prenom`, `telephone`, `longitude`, `latitude`) VALUES
(1, 'Mendes', 'Sam', '0620122015', '655849874', '6549877'),
(2, 'Glen', 'John', '0619811989', '5469489', '98674981');

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NULL,
  `prenomClient` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;

INSERT INTO `client` (`idClient`, `nomClient`, `prenomClient`, `email`, `telephone`) VALUES
(1, 'Roger', 'Moore', 'roger.moore@gmail.com', '065459654'),
(2, 'Timothy', 'Dalton', 'timothy.dalton@gmail.com', '0236416546');

-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `numeroRue` SMALLINT NULL,
  `voie` VARCHAR(45) NULL,
  `codePostal` SMALLINT NULL,
  `ville` VARCHAR(45) NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idAdresse`, `Client_idClient`),
  INDEX `fk_Adresse_Client1_idx` (`Client_idClient` ASC),
  CONSTRAINT `fk_Adresse_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `adresse` (`idAdresse`, `numeroRue`, `voie`, `codePostal`, `ville`, `Client_idClient`) VALUES
(5, 18, 'rue de Siam', 29200, 'Brest', 1),
(6, 23, 'Blv des Français Libres', 29200, 'Brest', 2);

-- -----------------------------------------------------
-- Table `mydb`.`Plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plat` (
  `idPlat` INT NOT NULL AUTO_INCREMENT,
  `nomPlat` VARCHAR(45) NULL,
  `photoPlat` BLOB NULL,
  `datePlat` DATE NULL,
  PRIMARY KEY (`idPlat`))
ENGINE = InnoDB;

INSERT INTO `plat` (`idPlat`, `nomPlat`, `photoPlat`, `datePlat`) VALUES
(1, 'Risotto', NULL, '2019-12-29'),
(2, 'Pâtes au sel', NULL, '2019-12-30');

-- -----------------------------------------------------
-- Table `mydb`.`Dessert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dessert` (
  `idDessert` INT NOT NULL AUTO_INCREMENT,
  `nomDessert` VARCHAR(45) NULL,
  `photoDessert` BLOB NULL,
  `dateDessert` DATE NULL,
  PRIMARY KEY (`idDessert`))
ENGINE = InnoDB;

INSERT INTO `dessert` (`idDessert`, `nomDessert`, `photoDessert`, `dateDessert`) VALUES
(1, 'Tiramisu', NULL, '2019-12-29'),
(2, 'Brownie', NULL, '2019-12-30');



-- -----------------------------------------------------
-- Table `mydb`.`Chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chef` (
  `idChef` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idChef`))
ENGINE = InnoDB;

INSERT INTO `chef` (`idChef`, `prenom`, `nom`) VALUES
(1, 'Pierce', 'Brosnan'),
(2, 'Sean', 'Connery');


-- -----------------------------------------------------
-- Table `mydb`.`MenuDuJour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MenuDuJour` (
  `idMenuDuJour` INT NOT NULL AUTO_INCREMENT,
  `nomMenu` VARCHAR(45) NULL,
  `dateMenu` DATE NULL,
  `nomPlat` VARCHAR(45) NULL,
  `nomDessert` VARCHAR(45) NULL,
  `Plat_idPlat` INT NOT NULL,
  `Dessert_idDessert` INT NOT NULL,
  `Chef_idChef` INT NOT NULL,
  PRIMARY KEY (`idMenuDuJour`, `Plat_idPlat`, `Dessert_idDessert`, `Chef_idChef`),
  INDEX `fk_MenuDuJour_Plat1_idx` (`Plat_idPlat` ASC),
  INDEX `fk_MenuDuJour_Dessert1_idx` (`Dessert_idDessert` ASC),
  INDEX `fk_MenuDuJour_Chef1_idx` (`Chef_idChef` ASC),
  CONSTRAINT `fk_MenuDuJour_Plat1`
    FOREIGN KEY (`Plat_idPlat`)
    REFERENCES `mydb`.`Plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MenuDuJour_Dessert1`
    FOREIGN KEY (`Dessert_idDessert`)
    REFERENCES `mydb`.`Dessert` (`idDessert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MenuDuJour_Chef1`
    FOREIGN KEY (`Chef_idChef`)
    REFERENCES `mydb`.`Chef` (`idChef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NULL,
  `heureCommande` TIME NULL,
  `prixCommande` DECIMAL NULL,
  `modePaiement` VARCHAR(45) NULL,
  `statutCommande` ENUM('ATTENTE', 'EN LIVRAISON', 'LIVREE') NULL,
  `Livreur_idLivreur` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Adresse_idAdresse` INT NOT NULL,
  `Adresse_idClient` INT NOT NULL,
  `MenuDuJour_idMenuDuJour` INT NOT NULL,

  PRIMARY KEY (`idCommande`, `Livreur_idLivreur`, `Client_idClient`, `Adresse_idAdresse`, `Adresse_idClient`, `MenuDuJour_idMenuDuJour`),
  INDEX `fk_Commande_Livreur1_idx` (`Livreur_idLivreur` ASC),
  INDEX `fk_Commande_Client1_idx` (`Client_idClient` ASC),
  INDEX `fk_Commande_Adresse1_idx` (`Adresse_idAdresse` ASC, `Adresse_idClient` ASC),
  INDEX `fk_Commande_MenuDuJour1_idx` (`MenuDuJour_idMenuDuJour` ASC),
  CONSTRAINT `fk_Commande_Livreur1`
    FOREIGN KEY (`Livreur_idLivreur`)
    REFERENCES `mydb`.`Livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_MenuDuJour1`
    FOREIGN KEY (`MenuDuJour_idMenuDuJour`)
    REFERENCES `mydb`.`MenuDuJour` (`idMenuDuJour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StockLivreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StockLivreur` (
  `nombreDessert` DECIMAL NULL,
  `nombrePlats` DECIMAL NULL,
  `Livreur_idLivreur` INT NOT NULL,
  INDEX `fk_StockLivreur_Livreur1_idx` (`Livreur_idLivreur` ASC),
  CONSTRAINT `fk_StockLivreur_Livreur1`
    FOREIGN KEY (`Livreur_idLivreur`)
    REFERENCES `mydb`.`Livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DispoLivreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DispoLivreur` (
  `disponible` enum(DISPONIBLE,NON DISPONIBLE),
  `Livreur_idLivreur` INT NOT NULL,
  INDEX `fk_DispoLivreur_Livreur1_idx` (`Livreur_idLivreur` ASC),
  CONSTRAINT `fk_DispoLivreur_Livreur1`
    FOREIGN KEY (`Livreur_idLivreur`)
    REFERENCES `mydb`.`Livreur` (`idLivreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
